replicas: 1

nodeSelector:
  role: core
tolerations:
  - key: "role"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

resources:
  limits:
   cpu: 100m
   memory: 64Mi
  requests:
   cpu: 10m
   memory: 32Mi
