---
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false

serviceAccounts:
  server:
    create: false
  alertmanager:
    create: false
  pushgateway:
    create: false
  nodeExporter:
    create: false

server:
  replicaCount: 1

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - "${prometheus_hostname}"

  persistentVolume:
    enabled: true
    size: 4Gi
    storageClass: "${storage_class}"
  retention: 24h

  statefulSet:
    enabled: false

  nodeSelector:
    role: core
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"

  resources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi

