{
 "title": "K8s Overview",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [ "eks" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable{resource=\"pods\", node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\"}) / sum(kube_node_status_allocatable{node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$node\"}) / sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\", node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "POD CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "POD CPU Cores Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_user_seconds_total{container=\"\", instance=~\"$node\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "POD Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "POD Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_memory_working_set_bytes{container=~\"\", instance=~\"$node\", namespace=~\"$namespace\"}[5m]) * 100)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=~\"cpu\", namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Activated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  }
 ]
}