---
controller:
  nodeSelector:
    role: core
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
  updateStrategy:
    type: Recreate
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  service:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    annotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
    nodePorts:
      https: ${k8s_nginx_https_host_port}
      http: ${k8s_nginx_http_host_port}
  metrics:
    port: 10254
    enabled: true
  admissionWebhooks:
    patch:
      nodeSelector:
        role: core
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "core"
          effect: "NoSchedule"
  config:
    proxy-real-ip-cidr: "${vpc_cidr}"
    use-http2: "true"
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    error-log-level: "warn"
    gzip-types: "application/soap+xml"
    large-client-header-buffers: 4 64k
    proxy-body-size: "32m"
    proxy-buffer-size: "8k"
    proxy-connect-timeout: "2"
    proxy-next-upstream-tries: "0"
    proxy-read-timeout: "300"
    proxy-send-timeout: "300"
    client-body-buffer-size: "32m"
    server-name-hash-bucket-size: "128"
    server-name-hash-max-size: "1024"
    use-gzip: "true"
    log-format-upstream: <<-EOF
      $time_iso8601 | $remote_addr | $request | $status | $body_bytes_sent | $request_time | $http_referer | $http_user_agent | $host | $http_x_forwarded_for | $http_x_bf_tracing_traceid | $http_x_bf_tracing_parent_spanid | $http_x_bf_tracing_spanid | OTHERS | $http_x_bf_tracing_hostid | $proxy_add_x_forwarded_for | $request_length | $upstream_response_time | $upstream_addr | $upstream_cache_status | $upstream_connect_time | $upstream_cookie_name | $upstream_header_time | $upstream_http_name | $upstream_response_length | $upstream_status | $connection_requests
      EOF
defaultBackend:
  enabled: yes
  image:
    repository: registry.k8s.io/defaultbackend-arm64
  nodeSelector:
    role: core
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
  replicaCount: 0
